### ISSUE TITLE
GUN Docs shouldn't be visible on homepage

### ISSUE THREAD

**Issue by code3z** [estebanrfp/gun.eco#15]
GUN Docs is visible on the gun homepage when:
1. On mobile: swipe right, docs table of contents is shown. This really messes up the mobile navigation, especially because the gun homepage has some x-overflow
2. On desktop: hovering a certain area will make the search bar appear, even though it isn't supposed to be there
3. Without javascript: a minimal docs template is shown where the homepage should be and *there is no noscript message*

**Comment by estebanrfp** [comment]
but they are two parallel projects, the landing page and the documentation platform, please do not add issues without identifying the repos.

**Comment by code3z** [comment]
I don’t see how the bugs I described could be intended behavior

**Comment by estebanrfp** [comment]
what I meant is that the behavior is the one that is expected, the one that you want to change

**Comment by code3z** [comment]
Yeah, it’s bad UX tho…
As are the other issues you closed
They may not be breaking issues but they are bad and together cause bad UX on the site. IMO you should consider using docusaurus or something

**Comment by estebanrfp** [comment]
you are not understanding, the documents are dynamic, the platform works correctly, what happens is that the landing page is being compiled from another repository, it is a temporary solution that was given, but it has nothing to do with the structure of the platform, they are two different repositories, you should check for broken links and other items in the dynamic list and in the documents, not here, the way in which the data is being pulled is the one that was requested, and the platform renders the documents in the format that was requested. but the problem lies in the loading of the landing page files. but at the moment we can't fix it. the documentation and the system is not the problem. many get confused and then verify this.
